---
- hosts: localhost
  become: yes
  tasks:
    - name: install apache on redhat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution == "RedHat"
    - name: install apache on ubuntu
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    - name: print free memory
      debug:
        msg: "free memory is {{ ansible_memory_mb.real.free }}"